### ISSUE TITLE
Thanks! Android?

### ISSUE THREAD

**Issue by WanHonghui204** [mautini/google-assistant-java-demo#2]
Hi, thank you very much for the great work!! Any chance you can port it to Android? That would be truly awesome :)

**Comment by mautini** [comment]
Hi,

Thanks for your support and sorry for the very late response.

Currently I don't have plan to port it to Android but it mustn't be a big deal. The code is written in Java so you just have to adapt it to consider the specificities of the plateform (audio input / output, storage of the authentication token, retrieval of the authorization code...)

Furthermore, since the release of this lib, Google Assistant is available on all the Android devices so I don't think its very pertinent to port it.
